import type { Challenge } from "../types";

export const languageDrills: Challenge = {
  id: "language-drills",
  mode: "quick",
  level: "beginner",
  category: "personal",
  estimatedMinutes: 30,
  title: {
    en: "He Cannot Tell If It Is Right",
    it: "Non può sapere se è giusto",
  },
  scenario: {
    en: "Bruno is six months into European Portuguese and does twenty minutes most mornings. He runs out of exercises constantly and wants something that generates more. He is also aware that if one of those exercises is wrong, he will not notice, and he will learn it.",
    it: "Bruno studia portoghese europeo da sei mesi e ci dedica venti minuti quasi ogni mattina. Finisce gli esercizi in continuazione e vorrebbe qualcosa che gliene generi altri. È anche consapevole che se uno di quegli esercizi è sbagliato, non se ne accorgerà, e lo imparerà così.",
  },
  constraints: [
    {
      en: "He is a beginner. Verification by the person using it — the thing every other design leans on — is not available here.",
      it: "È un principiante. La verifica da parte di chi lo usa — la cosa su cui si appoggia ogni altro design — qui non è disponibile.",
    },
    {
      en: "What he needs practice on is whatever he keeps getting wrong, and nothing currently records that.",
      it: "Ciò su cui deve esercitarsi è quello che continua a sbagliare, e al momento non c'è niente che lo registri.",
    },
    {
      en: "European Portuguese, not Brazilian. The two differ in ways that matter, and generated material drifts towards whichever has more text behind it.",
      it: "Portoghese europeo, non brasiliano. I due differiscono in modi che contano, e il materiale generato scivola verso quello che ha più testo alle spalle.",
    },
  ],
  nudge: {
    en: "The person using this cannot check whether it is right. Work out what that removes from your design, and what has to go in its place.",
    it: "La persona che lo usa non può verificare se sia giusto. Capisci cosa toglie questo al tuo design, e cosa deve andare al suo posto.",
  },
  approach: {
    summary: {
      en: "Arrange verified material rather than authoring language, derive the answer from the source, and let his own mistakes choose what comes next.",
      it: "Ricomponi materiale verificato invece di scrivere lingua, ricava la risposta dalla fonte, e lascia che siano i suoi errori a scegliere cosa viene dopo.",
    },
    steps: [
      {
        en: "Generate exercises from a verified source — a textbook chapter, a graded reader, a sentence bank — rather than from nothing. The model's job is to arrange known-correct material, not to author a language it is being trusted to teach.",
        it: "Genera gli esercizi da una fonte verificata — un capitolo di un manuale, un libro graduato, una raccolta di frasi — invece che dal nulla. Il compito del model è ricomporre materiale già corretto, non scrivere una lingua che gli stai affidando da insegnare.",
      },
      {
        en: "Derive the answer key from the source rather than producing it alongside the question. An answer generated by the same call that generated the question is not a check on it.",
        it: "Ricava la chiave di correzione dalla fonte invece di produrla insieme alla domanda. Una risposta generata dalla stessa chiamata che ha generato la domanda non ne è una verifica.",
      },
      {
        en: "Record what he gets wrong and let that select what comes next. This is a database question, and it is where the actual value of a tutor lives.",
        it: "Registra cosa sbaglia e lascia che sia quello a scegliere cosa viene dopo. È una questione di base dati, ed è lì che sta il valore vero di un insegnante.",
      },
      {
        en: "Pin the variety explicitly and then test that it held. \"European Portuguese\" inside a prompt is a request; the output needs checking against something that knows the difference.",
        it: "Fissa la varietà in modo esplicito e poi verifica che abbia tenuto. «Portoghese europeo» dentro un prompt è una richiesta; l'output va confrontato con qualcosa che sappia la differenza.",
      },
      {
        en: "Give him one visible way to flag an exercise that feels off, and actually read those flags. He cannot judge correctness, but he can notice when two exercises contradict each other.",
        it: "Dagli un modo visibile per segnalare un esercizio che non convince, e leggi davvero quelle segnalazioni. Non può giudicare la correttezza, ma può accorgersi quando due esercizi si contraddicono.",
      },
    ],
  },
  pitfalls: [
    {
      en: "The ordinary safety net — a person noticing the output is wrong — does not exist for a learner. Every design decision that quietly assumed review has to be replaced with something else.",
      it: "La solita rete di sicurezza — una persona che si accorge che l'output è sbagliato — per chi impara non esiste. Ogni scelta di progetto che dava per scontata una revisione va sostituita con qualcos'altro.",
    },
    {
      en: "Generated questions with generated answers. Both come from the same place, they agree with each other perfectly, and their agreement is evidence of nothing whatsoever.",
      it: "Domande generate con risposte generate. Vengono entrambe dallo stesso posto, concordano perfettamente fra loro, e la loro concordanza non è prova di assolutamente niente.",
    },
    {
      en: "Silent drift into Brazilian forms. It happens in exactly the places a beginner cannot see, and unlearning a form is considerably harder than learning it.",
      it: "Lo scivolamento silenzioso verso forme brasiliane. Avviene esattamente nei punti che un principiante non può vedere, e disimparare una forma è parecchio più difficile che impararla.",
    },
    {
      en: "Exercises that are grammatical, correct, and nothing like anything anyone says. He becomes fluent in a register that marks him as a textbook the moment he opens his mouth.",
      it: "Esercizi grammaticali, corretti e che non somigliano a niente di ciò che dice qualcuno. Diventa sciolto in un registro che lo marchia come un manuale nel momento in cui apre bocca.",
    },
  ],
  starterPrompt: {
    en: "I want generated practice exercises for European Portuguese. The problem is that I'm a beginner — if an exercise is wrong I'll just learn it wrong and never find out. Ask me where the material should come from, given that I can't be the one checking it.",
    it: "Voglio esercizi di pratica generati per il portoghese europeo. Il problema è che sono principiante: se un esercizio è sbagliato lo imparerò sbagliato e non lo scoprirò mai. Chiedimi da dove dovrebbe arrivare il materiale, visto che non posso essere io a verificarlo.",
  },
};
